# Generated by Django 3.0.2 on 2020-01-10 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recent_search', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recentsearch',
            old_name='spotifyId',
            new_name='deezerId',
        ),
    ]
