# Generated by Django 3.0.2 on 2020-01-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='spotifyId',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
