# Generated by Django 3.0.2 on 2020-01-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_auto_20200109_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='spotifyId',
            field=models.CharField(max_length=64),
        ),
    ]
