# Generated by Django 3.0.2 on 2020-01-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0005_auto_20200110_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='deezerId',
            field=models.IntegerField(),
        ),
    ]
